---
exp_name: GRAN
exp_dir: exp/GRAN
runner: GranRunner
use_horovod: false
use_gpu: true
device: cuda:0
gpus: [0]
seed: 1234
dataset:
  loader_name: GRANData
  name: grid_embed
  data_path: data/
  node_order: DFS # k_core/BFS/degree_decent
  train_ratio: 0.8
  dev_ratio: 0.2
  num_subgraph_batch: 25 #10 # number of subgraphs per mini-batch
  num_fwd_pass: 1
  has_node_feat: true
  is_save_split: false
  is_sample_subgraph: true # set to true if you want to sample subgraphs
  is_overwrite_precompute: true
  is_noisy: true
  noise_std: 0.2 # If graphs are normalized we need lower noise
model:
  name: GRANMixtureBernoulli
  num_mix_component: 1
  is_sym: true
  block_size: 1
  sample_stride: 1
  max_num_nodes: 25
  hidden_dim: 128
  embedding_dim: 128
  node_embedding_dim: 2
  num_GNN_layers: 7
  num_GNN_prop: 1
  num_canonical_order: 1
  dimension_reduce: true
  has_attention: true
  edge_weight: 1.0e+0
train:
  optimizer: Adam
  lr_decay: 0.5
  lr_decay_epoch: [30, 90, 150, 250, 350, 500, 700, 1000, 1300, 1500, 1800, 2000]
  num_workers: 4
  max_epoch: 3000
  batch_size: 4
  display_iter: 10
  snapshot_epoch: 250
  valid_epoch: 50
  lr: 5.0e-4
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_epoch: 160
  resume_dir: exp/GRAN/GRANMixtureBernoulli_grid_embed_2024-Apr-23-14-18-38_4071567/
  resume_model: model_snapshot_0003000.pth
test:
  batch_size: 1
  num_workers: 1
  num_test_gen: 1 # number of generated samples
  is_vis: true
  num_vis: 1
  vis_num_row: 1 # visualize `num_vis` samples in `vis_num_row` rows
  animated_vis: true
  num_animations: 1 ## Number of graphs to save animation for
  shuffle: true
  test_model_dir: exp/GRAN/GRANMixtureBernoulli_grid_embed_2024-Apr-23-15-20-33_414930/
  test_model_name: model_snapshot_0002000.pth